CREATE SCHEMA `db_sis_proyectos` ;

USE db_sis_proyectos;

CREATE TABLE TRABAJADOR(
COD_TRABAJADOR				INTEGER NOT NULL AUTO_INCREMENT,
COD_PROVEEDOR				INTEGER NOT NULL,
DNI							CHAR(10) NOT NULL,
NOMBRES						VARCHAR(20) NOT NULL,
APELLIDOS					VARCHAR(20) NOT NULL,
SEXO						CHAR(1) NULL,
TELEFONO					CHAR(20) NULL,
CORREO_ELECTRONICO			VARCHAR(50) NULL,
NUM_CELULAR					CHAR(20) NULL,
DIRECCION					VARCHAR(50) NULL,
ESTADO						CHAR(1) NULL,
PRIMARY KEY (COD_TRABAJADOR)
);

CREATE TABLE CLIENTE(
COD_CLIENTE					INTEGER NOT NULL AUTO_INCREMENT,
RUC			 				CHAR(20) NOT NULL,
RAZON_SOCIAL				VARCHAR(100) NULL,
REPRESENTANTE_LG			VARCHAR(50) NULL,
DIRECCION					VARCHAR(50) NULL,
TELEFONO					CHAR(20) NULL,
CORREO_ELECTRONICO			VARCHAR(50) NULL,
ESTADO						CHAR(1) NULL,
PRIMARY KEY (COD_CLIENTE)
);

CREATE TABLE PROVEEDOR(
COD_PROVEEDOR				INTEGER NOT NULL AUTO_INCREMENT,
RUC							CHAR(20) NOT NULL,
RAZON_SOCIAL				VARCHAR(100) NULL,
REPRESANTE_LG				VARCHAR(50) NULL,
DIRECCION					VARCHAR(50) NULL,			
TELEFONO					CHAR(20) NULL,
CORREO_ELECTRONICO			VARCHAR(50) NULL,
ESTADO						CHAR(1) NULL,
PRIMARY KEY (COD_PROVEEDOR)
);

CREATE TABLE CRONOGRAMA(
COD_ACTIVIDAD				INTEGER NOT NULL AUTO_INCREMENT,
COD_PROYECTO				INTEGER NOT NULL,
DESC_ACTIVIDAD				VARCHAR(100) NULL,
FECHA_INICIO				DATE NULL,
FECHA_TERMINO				DATE NULL,
AVANCE						CHAR(30) NULL,
ESTADO						CHAR(1) NULL,
PRIMARY KEY (COD_ACTIVIDAD)
);

CREATE TABLE PROYECTO(
COD_PROYECTO				INTEGER NOT NULL AUTO_INCREMENT,
COD_CLIENTE					INTEGER NOT NULL,
COD_EQUIPO					INTEGER NOT NULL,
NOMBRE_PROYECTO				VARCHAR(100) NOT NULL,
DESCRIPCION					VARCHAR(200) NULL,
ESTADO						CHAR(1) NULL,
PRIMARY KEY (COD_PROYECTO)
);

CREATE TABLE EQUIPO_DESARROLLO(
COD_EQUIPO					INTEGER NOT NULL AUTO_INCREMENT,
DESCRIPCION					VARCHAR(100) NULL,
ESTADO						CHAR(1) NULL,
PRIMARY KEY (COD_EQUIPO)
);

CREATE TABLE EQUIPO_TRABAJADOR(
COD_EQUIPO					INTEGER NOT NULL,
COD_TRABAJADOR				INTEGER NOT NULL,
CARGO						VARCHAR(20) NULL,
ESTADO						CHAR(1) NULL,
PRIMARY KEY (COD_EQUIPO, COD_TRABAJADOR)
);

CREATE TABLE USUARIOS(
    CODUSUARIO INTEGER NOT NULL AUTO_INCREMENT,
    NOMBRES CHAR(50) NOT NULL,
    APEPATERNO CHAR(50) NOT NULL,
    APEMATERNO CHAR(50) NOT NULL,
    CELULAR VARCHAR(15) NOT NULL,
    CORREO CHAR(100) NOT NULL, 
    USUARIO CHAR(50) NOT NULL,
    CONTRASENA VARCHAR(255) NOT NULL,
    ESTADO CHAR(1) NOT NULL,
    PRIMARY KEY(CODUSUARIO)
);

ALTER TABLE TRABAJADOR 
ADD CONSTRAINT FK_TRABAJADOR_PROVEEDOR FOREIGN KEY (COD_PROVEEDOR)
REFERENCES PROVEEDOR(COD_PROVEEDOR);

ALTER TABLE CRONOGRAMA
ADD CONSTRAINT FK_CRONOGRAMA_PROYECTO FOREIGN KEY (COD_PROYECTO)
REFERENCES PROYECTO(COD_PROYECTO);

ALTER TABLE EQUIPO_TRABAJADOR
ADD CONSTRAINT FK_EQUIPOTRABAJADOR_TRABAJADOR FOREIGN KEY (COD_TRABAJADOR)
REFERENCES TRABAJADOR(COD_TRABAJADOR);

ALTER TABLE PROYECTO
ADD CONSTRAINT FK_PROYECTO_CLIENTE FOREIGN KEY (COD_CLIENTE)
REFERENCES CLIENTE(COD_CLIENTE);

ALTER TABLE PROYECTO
ADD CONSTRAINT FK_PROYECTO_EQUIPO FOREIGN KEY (COD_EQUIPO)
REFERENCES EQUIPO_DESARROLLO(COD_EQUIPO);

ALTER TABLE EQUIPO_TRABAJADOR
ADD CONSTRAINT FK_EQUIPO_TRABAJADOR_DESARROLLO FOREIGN KEY (COD_EQUIPO)
REFERENCES EQUIPO_DESARROLLO (COD_EQUIPO);

INSERT INTO CLIENTE 
	(RUC,RAZON_SOCIAL,REPRESENTANTE_LG,DIRECCION,TELEFONO,CORREO_ELECTRONICO,ESTADO) 
VALUES
	(10764000215,'CLARO','Manuel Gonzales','Jr.Abancay 310','9214888351','claro@gmail.com',1),
	(10774000216,'SUNAT','Pedro Vasquez','Av. Brasil','995376601','sunat@gmai.com',1),
	(10784000217,'Luz del Sur','José Quispe','San Vicente-Cañete','911114826','luz_sur@gmail.com',1),
	(10794000218,'TOTTUS','Axel Sánchez','Cañete','900913754','tottus@gmail.com',2),
	(10804000219,'Sodimac','Keny Gutierres','Lima','999682405','sodimac@gmai.com',1);

INSERT INTO PROVEEDOR
	(RUC,RAZON_SOCIAL,REPRESANTE_LG,DIRECCION,TELEFONO,CORREO_ELECTRONICO,ESTADO)
VALUES
	(20935000220,'TMGROUP','Miguel Rodriguez','San Miguel','99062259','TMGROUP@gmai.com',1),
	(20945000221,'DELAWERE','Jesus Alzamora','San Luis','981734812','DELAWERE@gmail.com',1),
	(20955000222,'INDRA','Paul Cabrera','San Luis','972645932','INDRA@gmail.com',2),
	(20965000223,'ENTITIDATA','Manuel Ramos','LIMA','96375045','ENTITIDATA@gmail.com',2),
	(20975000224,'GEIST','Ruben Quiroz','LIMA','95486156','GEIST@gmial.com',1);
INSERT INTO TRABAJADOR
	(COD_PROVEEDOR,DNI,NOMBRES,APELLIDOS,SEXO,TELEFONO,CORREO_ELECTRONICO,NUM_CELULAR,DIRECCION,ESTADO)	
VALUES
	(1,2794426,'Julio Enrique','Ceballos Guerra','M','019423581','JulioCeballos@gmail.com','917265157','Imperial',1),
	(2,43218954,'Mariana Luz','García Montes','F','017098425','MarianaGarcía@gmail.com','976428457','Quilmaná',1),
	(3,73534899,'Felipe Celestino','Magallanes Perez','M','012397426','FelipeMagallanes@gmail.com','912365478','San Vicente',0),
	(4,48745968,'Oscar','Lopez Vega','M','-','OscarLopez@gmail.com','917390961','Cerro Azul',1),
	(5,73290944,'Luisa','Rojas Matos','F','017425943','LuisaMatos@gmail.com','955440655','Chincha',0);
SELECT * FROM PROVEEDOR;
INSERT INTO EQUIPO_DESARROLLO
	(DESCRIPCION,ESTADO)
VALUES
	('EQUIPO 1-TMGROUP',1),
	('EQUPO 2-TMGROUP',1),
	('EQUIPO 1-GEIST',1),
	('EQUIPO 2-INDRA',0),
	('EQUIPO 1-DELAWERE',1);

SELECT * FROM CLIENTE;
SELECT * FROM EQUIPO_DESARROLLO;
SELECT * FROM PROYECTO;

INSERT INTO PROYECTO 
	(COD_CLIENTE,COD_EQUIPO,NOMBRE_PROYECTO,DESCRIPCION,ESTADO)
VALUES
	(1,1,'SUNAT','Sistema para la gestión de reclutamiento y selección de personal',2),
	(2,2,'Cañete LNG-CLARO','Gestión de nómina de trabajadores',1),
	(3,3,'Computrabajo-Cañete','Proceso de intermedicación laboral',1),
	(4,4,'Luz del Sur','Gestión de nómina de trabajadores',1),
	(5,5,'Oferta laboral-Cajeros y supervisores para Tottus-Cañete','Sistema para la gestión de reclutamiento y selección de personal',2);

INSERT INTO CRONOGRAMA
	(COD_PROYECTO,DESC_ACTIVIDAD,FECHA_INICIO,FECHA_TERMINO,AVANCE,ESTADO)
VALUES
	(11,'Entrega e informe de Proyecto','2020/05/20','2020/08/21','CULMINADO',2),
	(12,'Corregir errores en el desarrollo del proyecto','2021/02/15','2021/03/16','PUNTOS POR SUBSANAR',1),
	(13,'Entrega e informe final de Proyecto','2021/10/14','2021/12/15','CULMINADO',2),
	(14,'Revision de avance de Proyecto','2021/06/10','2021/09/11','REVISION',1),
	(15,'Entrega e informe de Proyecto','2022/05/20','2022/08/21','CULMINADO',2);

SELECT * FROM TRABAJADOR;

INSERT INTO EQUIPO_TRABAJADOR
	(COD_EQUIPO,COD_TRABAJADOR,CARGO,ESTADO)
VALUES
	(1,11,'Programador',1),
	(2,12,'Analista',1),
	(3,13,'Programador',1),
	(4,13,'Tester',1),
	(5,15,'Analista',1);

INSERT INTO USUARIOS
	  (NOMBRES,APEPATERNO,APEMATERNO,CELULAR,CORREO,USUARIO,CONTRASENA,ESTADO) 
VALUES
     ('Brayan Jhoel ','Espinoza','Sánchez','921071231','brayan.espinoza.sanchez.18@gmail.com','Jhoel26','$2y$10$GH4T5CKec4.RSPqx44RmEeqZq6GJRqjhYuotx9dUtOuVyPD4xC5wK','1'),
     ('Nielhs Amedt','Davalos','Herrera','949973144','nielhsdavalos04@gmail.com','AmedtDh','$2y$10$DNbHeMUzJfhTwUsl8UlULOfmESO6x04CMlxjo2nNNe2K9eoHx.Jre','1'),
     ('Rubek Jeampier','Quispe','Velasquez','917390964','rubeks29@gmail.com','RubeksQuispe','$2y$10$CrnBMiYXWiipduTeC9U3FeL8bLwQcH/lgPz3bFmMtrGqtFB.d.fme', '1'),
	 ('Jose Eduardo','Sanchez','Navarro','989041249','joseeduardo.28.02.03@gmail.com','EduardoSnv','$2y$10$RyeIGyZsbsW9qjXUhf1dPup0Dp1ljzS92DLReCHNMNx81DDdc/6QC','1');

SELECT * FROM CLIENTE;

SELECT * FROM PROVEEDOR;

SELECT * FROM TRABAJADOR;

SELECT * FROM CRONOGRAMA WHERE ESTADO = '1' ORDER BY COD_PROYECTO;

SELECT * FROM EQUIPO_DESARROLLO;

SELECT * FROM PROYECTO;

SELECT * FROM  EQUIPO_TRABAJADOR;

SELECT * FROM USUARIOS;

INSERT INTO CLIENTE (RUC, RAZON_SOCIAL, REPRESENTANTE_LG, DIRECCION, TELEFONO,CORREO_ELECTRONICO,ESTADO)
VALUES				( 10814000220, 'TOUR AIR LINE', 'Pedro Quispe', 'Huacho', 980752143, 'tourarline@gmail', 1);

SELECT * FROM PROYECTO;
-- update proyecto set estado = 1 where cod_proyecto =30120;
INSERT INTO CRONOGRAMA
	(COD_PROYECTO,DESC_ACTIVIDAD,FECHA_INICIO,FECHA_TERMINO,AVANCE,ESTADO)
VALUES
	(11,'Modelamiento inicial','2020/08/24','2020/09/15','PENDIENTE',1),
	(12,'Pase a producción','2021/03/18','2021/04/10','PENDIENTE',1),
	(13,'Diseño de interfaz','2022/09/16','2021/10/18','PENDIENTE',1);

	
SELECT * FROM CRONOGRAMA WHERE COD_PROYECTO = 10020;

UPDATE USUARIOS 
   SET CONTRASENA = '$2y$08$dJmQkvXc3o49xkkLOe5p4OobYyzodDUKKNiEn.orlnQ83bpbb.JWG'
 WHERE CODUSUARIO = 4;


UPDATE USUARIOS 
   SET CONTRASENA = '$2y$08$J4qNabbWSf84uZrBKjmSJOhHwgGZTpBUr.ufCx9D63afOLm952bOm'
 WHERE CODUSUARIO = 3;

 
UPDATE USUARIOS 
   SET CONTRASENA = '$2y$08$ElUMIu7O/V5GYYINOeFxp.3sq2w7Y8x1fNn3Vagm2qfcpsTVAvAFq'
 WHERE CODUSUARIO = 2;

 
UPDATE USUARIOS 
   SET CONTRASENA = '$2y$10$GNngwimju59kyIR2cBziVOwV1PLjcYqLWvW8mXAx5NXA/H0vfNAQK'
 WHERE CODUSUARIO = 1;

 UPDATE CRONOGRAMA
	SET DESC_ACTIVIDAD = 'Implementación de BD'
	WHERE COD_ACTIVIDAD = 2702;

UPDATE PROYECTO
SET ESTADO = 1
WHERE COD_PROYECTO = 30020;

 UPDATE CRONOGRAMA
	SET ESTADO = 1
	WHERE COD_ACTIVIDAD IN (2702, 2704, 2706);

 UPDATE EQUIPO_TRABAJADOR
	SET  CARGO = 'Programador FE'
	WHERE COD_TRABAJADOR = 202 AND COD_EQUIPO = 300;

 UPDATE EQUIPO_TRABAJADOR
	SET CARGO ='Programador BE'
	WHERE COD_TRABAJADOR = 200 AND COD_EQUIPO = 302;

 UPDATE EQUIPO_TRABAJADOR
	SET CARGO = 'Gefe de Proyecto'
	WHERE COD_TRABAJADOR = 203 AND COD_EQUIPO = 304;

SELECT * FROM EQUIPO_DESARROLLO;
SELECT * FROM EQUIPO_TRABAJADOR;

INSERT INTO EQUIPO_TRABAJADOR 
			(COD_EQUIPO,COD_TRABAJADOR,CARGO,ESTADO)
VALUES
			-- ('5','15','Analista','1'),
			('5','11','Tester','1'),
			('5','13','Programador FE','1'),
			('5','14','Gefe de Proyecto','1'),
			('1','15','Programador FE','1'),
			-- ('1','11','Programador BE','1'),
			('1','12','Tester','1'),
			('1','13','Gefe de Proyecto','1'),
			('2','11','Programador FE','1'),
			-- ('2','12', 'Analista','1'),
			('2','13','Tester','1'),
			('2','14','Gefe de Proyecto','1'),
			('3','15','Programador FE', '1'),
			('3','12', 'Programador BE','1'),
			-- ('3','13','Analista','1'),
			('3','14','Gefe de Proyecto','1'),
			('4','15','Programador FE', '1'),
			('4','11','Programador BE','1'),
			('4','12','Analista','1'),
			('4','14','Tester','1');

 UPDATE  EQUIPO_TRABAJADOR
	SET CARGO = 'Programador BE'
	WHERE COD_TRABAJADOR = 203 AND COD_EQUIPO = 300;

	SELECT * FROM EQUIPO_TRABAJADOR;

	UPDATE EQUIPO_TRABAJADOR
	SET CARGO = 'Jefe de Proyecto'
	WHERE CARGO = 'Gefe de Proyecto';

-- QUERY DE LISTAR PROYECTOS
	SELECT P.NOMBRE_PROYECTO, E.DESCRIPCION AS EQUIPO_DESARROLLO, C.RAZON_SOCIAL, P.DESCRIPCION
	  FROM PROYECTO P
	  INNER JOIN CLIENTE C ON P.COD_CLIENTE = C.COD_CLIENTE
	  INNER JOIN EQUIPO_DESARROLLO E ON P.COD_EQUIPO = E.COD_EQUIPO;
	  
-- QUERY DETALLE DE PROYECTO
	SELECT P.COD_PROYECTO, NOMBRE_PROYECTO, P.DESCRIPCION, C.CORREO_ELECTRONICO, C.REPRESENTANTE_LG
	  FROM PROYECTO P
	  INNER JOIN CLIENTE C ON P.COD_CLIENTE = C.COD_CLIENTE
	  INNER JOIN EQUIPO_DESARROLLO E ON P.COD_EQUIPO = E.COD_EQUIPO
	 WHERE P.COD_PROYECTO ='10000';

ALTER TABLE USUARIOS
ADD TIPO_USUARIO CHAR(1) NOT NULL DEFAULT 'A';

-- ALTER TABLE USUARIOS
-- DROP CONSTRAINT DF__USUARIOS__TIPO_U__47DBAE45 ;

ALTER TABLE USUARIOS 
DROP COLUMN TIPO_USUARIO;

SELECT * FROM USUARIOS;

SELECT * FROM CLIENTE;

SELECT * FROM EQUIPO_DESARROLLO;

SELECT * FROM PROYECTO;

SELECT * FROM CRONOGRAMA;

UPDATE CLIENTE SET
RAZON_SOCIAL = 'ENTEL'
WHERE COD_CLIENTE = '7405';

UPDATE EQUIPO_DESARROLLO SET
DESCRIPCION = 'OXINERMING'
WHERE COD_EQUIPO = '1301';

SELECT * FROM CRONOGRAMA;

DELETE FROM CRONOGRAMA 
WHERE COD_ACTIVIDAD = '2716';


/* Estimar el tiempo que requiera cada proyecto como: la fecha de inicio y la fecha de culminación, 
   a partir del cronograma de tareas; para seguidamente dar pase a producción y continuar con el desarrollo de otro proyecto. */

   SELECT P.NOMBRE_PROYECTO AS 'Proyecto', MIN(C.FECHA_INICIO) AS 'Fecha Inicio Proyecto', MAX(C.FECHA_TERMINO) AS 'Fecha Fin Proyecto'
     FROM CRONOGRAMA C
	 INNER JOIN PROYECTO P ON C.COD_PROYECTO = P.COD_PROYECTO
	WHERE P.ESTADO != 0
	  AND C.ESTADO != 0
    GROUP BY P.NOMBRE_PROYECTO;

/* Quien es el jefe del equipo de desarrollo del proyecto. */

	SELECT P.NOMBRE_PROYECTO AS 'Proyecto', CONCAT(T.APELLIDOS,', ',T.NOMBRES) AS 'Jefe de Proyecto'
	  FROM PROYECTO P
	 INNER JOIN EQUIPO_TRABAJADOR ET ON P.COD_EQUIPO = ET.COD_EQUIPO
	 INNER JOIN TRABAJADOR T ON ET.COD_TRABAJADOR = T.COD_TRABAJADOR
	 WHERE P.ESTADO != 0
	   AND ET.CARGO = 'Jefe de Proyecto';

/* Cantidad de tareas por proyecto */

   SELECT P.NOMBRE_PROYECTO AS 'Proyecto', COUNT(C.COD_ACTIVIDAD) AS 'Cantidad de Tareas'
     FROM CRONOGRAMA C
	 INNER JOIN PROYECTO P ON C.COD_PROYECTO = P.COD_PROYECTO
	WHERE P.ESTADO != 0
	  AND C.ESTADO != 0
    GROUP BY P.NOMBRE_PROYECTO;